name: Run tests

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v1
      with:
       node-version: '15.x'
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Install dependencies
      run: | 
        pip install -r --upgrade pip
        pip install -r --upgrade jupyterlab
        pip install --upgrade pytest
        pip install --upgrade selenium
        pip install -e .

    - name: Run the jupyter lab server
      run: |
        jupyter lab &
        url=$(jupyter server list | tail -1 | awk '{print $1}')

    - uses: nanasess/setup-chromedriver@master
      with:
        # Optional: do not specify to match Chrome's version
        chromedriver-version: '92.0.4515.107'
    - run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
        python3 $GITHUB_WORKSPACE/tests/test.py $url

    - uses: actions/upload-artifact@v2
      with:
        name: quantum-screenshot
        path: './*.png'

